version: '3'
services:
  dns_server:
    build: dns
    #Para q este siempre el docker encendido
    restart: unless-stopped
    command: --addn-hosts=/etc/custom_hosts
    volumes:
      - ./dns/lista.txt:/etc/custom_hosts:ro
    networks:
      my_network:
        ipv4_address: 192.168.46.4
  cliente-firefox:
    image: kasmweb/firefox:1.14.0
    restart: unless-stopped
    ports:
      - 6901:6901
    environment:
      - VNC_PW=abc123. #Usuario kasm_user
    dns:
      - 192.168.46.4
    networks:
      my_network:
  cliente:
    build: cliente
    restart: unless-stopped
    dns:
      - 192.168.46.4
    networks:
      my_network:

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.46.0/24
